<?php

/*****************
	GENERAL SETTINGS
*****************/
$imSettings['search']['general'] = array(
	'menu_position' => 'left',
	'defaultScope' => array(
		'0' => 'index.php',
		'3' => 'emulador---nes.html',
		'4' => 'emulador---snes.html',
		'5' => 'emulador---wii-u.html',
		'7' => 'emulador---game-boy-c----advanced.html',
		'10' => 'emulador---nintendo-64.html',
		'11' => 'emulador---game-cube---wii.html',
		'18' => 'master-system.html',
		'20' => 'mega-driver.html',
		'21' => 'sega-saturn.html',
		'22' => 'dreamcast.html',
		'34' => 'nes-1.php',
		'35' => 'snes-1.php',
		'37' => 'nintendo-64-1.php',
		'38' => 'game-cube-1.html',
		'39' => 'wii-1.html',
		'40' => 'wii-u.html',
		'41' => 'switch.html',
		'44' => 'game-boy-game-boy-color.html',
		'45' => 'nintendo-ds.html',
		'46' => 'nintendo-3ds.html',
		'51' => 'game---watch.html',
		'53' => 'color-tv-game.php',
		'57' => 'master-system-1.html',
		'58' => 'mega-driver-1.html',
		'59' => 'sega-saturn-1.html',
		'60' => 'dreamcast-1.html',
		'61' => 'game-gear.html',
		'63' => 'historia.html',
		'64' => 'historia-da-nintendo.html',
		'65' => 'historia-2.html',
		'66' => 'virtual-boy.html',
		'67' => 'pokemon-mini.html',
		'68' => 'ique-player.html',
		'69' => 'nintendo-dsi.html',
		'70' => 'nintendo-2ds.html',
		'71' => 'game-boy-advanced-1.html',
		'77' => 'distribuicoes.html',
		'78' => 'internet.html',
		'81' => 'ubuntu.html',
		'90' => 'historia-4.html',
		'92' => 'console-ps1-one.html',
		'93' => 'playstation-2.html',
		'94' => 'playstation-3.html',
		'95' => 'playstation-4.html',
		'97' => 'historia-windows.html',
		'98' => 'historia-linux.html',
		'99' => 'historia-mac-os---mac-os-x.html',
		'108' => 'iphone-e-versoes.html',
		'109' => 'ipad-e-versoes.html',
		'111' => 'iphone.html',
		'112' => 'iphone-3g.html',
		'113' => 'iphone-3gs.html',
		'114' => 'iphone-4.html',
		'115' => 'iphone-4s.html',
		'116' => 'iphone-5.html',
		'117' => 'iphone-5c.html',
		'118' => 'iphone-6.html',
		'119' => 'iphone-6s-plus.html',
		'120' => 'iphone-6-plus.html',
		'122' => 'iphone-se.html',
		'123' => 'iphone-7.html',
		'124' => 'iphone-7-plus.html',
		'125' => 'iphone-8.html',
		'126' => 'iphone-8-plus.html',
		'127' => 'iphone-x.html',
		'128' => 'iphone-5s.html',
		'132' => 'ashtar-sheran.html',
		'133' => 'pessoas---seres.html',
		'134' => 'felinos.html',
		'135' => 'pleiades.html',
		'136' => 'carians.html',
		'137' => 'kardecismo.html',
		'138' => 'sobre-ocultismo.html',
		'139' => 'sobre-o-universo.php',
		'140' => 'iphone-6s-.html',
		'141' => 'android-alpha---1.x.x.html',
		'143' => 'windows-phone---historia-e-versoes.html',
		'144' => 'distribuicao-timeline.html',
		'145' => 'debian.html',
		'146' => 'manjaro.html',
		'147' => 'deepin.html',
		'148' => 'mint.html',
		'150' => 'elementary.html',
		'151' => 'opensuse.html',
		'152' => 'historia-bill-gates.html',
		'153' => 'iphone-xs---xs-max.html',
		'155' => 'iphone-xr.html',
		'157' => 'graficos-vendas-de-produtos-apple.html',
		'158' => 'historia-de-steve-jobs.html',
		'159' => 'criador-do-iphone.html',
		'161' => 'ios-1.html',
		'162' => 'ios-2.html',
		'163' => 'ios-3.html',
		'164' => 'ios-4.html',
		'165' => 'ios-5.html',
		'166' => 'ios-6.html',
		'167' => 'ios-7.html',
		'168' => 'ios-8.html',
		'169' => 'ios-9.html',
		'170' => 'ios-10.html',
		'171' => 'ios-11.html',
		'172' => 'ios-12.html',
		'174' => 'apple.php',
		'177' => 'historia-do-macintosh.html',
		'178' => 'ios-versoes.html',
		'179' => 'microsoft.php',
		'213' => 'ipad.html',
		'214' => 'ipad-2.html',
		'215' => 'ipad-3--geracao.html',
		'216' => 'mini-ipad.html',
		'217' => 'ipad-4--geracao.html',
		'218' => 'ipad-air.html',
		'219' => 'ipad-mini-2-visor-de-retina.html',
		'220' => 'ipad-air-2.html',
		'221' => 'ipad-mini-3.html',
		'222' => 'ipad-mini-4.html',
		'223' => 'ipad-pro-1--12,9-.html',
		'224' => 'ipad-pro-1--9,7-.html',
		'225' => 'ipad-2017.html',
		'226' => 'ipad-pro-2--12,9-.html',
		'227' => 'ipad-pro-2--10,5-.html',
		'228' => 'ipad-2018.html',
		'229' => 'ipad-pro-3--11-.html',
		'230' => 'ipad-mini-2019.html',
		'231' => 'ipad-pro-3--12,9-.html',
		'232' => 'ar-ipad-2019.html',
		'234' => 'emulador---switch.html',
		'235' => 'linux.php',
		'236' => 'distribuicoes-e-populares.html',
		'238' => 'lista-de-games-0-a-9.html',
		'239' => 'lista-de-games-a.html',
		'240' => 'lista-de-games-b.html',
		'241' => 'lista-de-games-c.html',
		'242' => 'lista-de-games-d.html',
		'243' => 'lista-de-games-e.html',
		'244' => 'lista-de-games-f.html',
		'245' => 'lista-de-games-g.html',
		'246' => 'lista-de-games-h.html',
		'247' => 'lista-de-games-i.html',
		'248' => 'lista-de-games-j.html',
		'249' => 'lista-de-games-k.html',
		'250' => 'lista-de-games-l.html',
		'251' => 'lista-de-games-m.html',
		'252' => 'lista-de-games-n.html',
		'253' => 'lista-de-games-o.html',
		'254' => 'lista-de-games-p.html',
		'255' => 'lista-de-games-q.html',
		'256' => 'lista-de-games-r.html',
		'257' => 'lista-de-games-s.html',
		'258' => 'lista-de-games-t.html',
		'259' => 'lista-de-games-u.html',
		'260' => 'lista-de-games-v.html',
		'261' => 'lista-de-games-w.html',
		'262' => 'lista-de-games-x.html',
		'263' => 'lista-de-games-y.html',
		'264' => 'lista-de-games-z.html',
		'292' => 'lista-geral-de-games.html',
		'295' => 'hardware.html',
		'296' => 'placa-mae.html',
		'297' => 'processadores.html',
		'298' => 'memoria-ram.html',
		'299' => 'emuladores-para-pc.html',
		'300' => 'emuladores-nintendo.html',
		'301' => 'formatacoes-de-windows.html',
		'302' => 'formatar-windows-1.0.html',
		'303' => 'cinturao-de-foton.html',
		'304' => 'historicos-dos-mapas-mundi.html',
		'305' => 'buraco-negro.html',
		'306' => 'credo-mutwa-zulus-e-repetilianos-parte-1.html',
		'307' => 'ocultismo-espiritual-multidimensional.php',
		'308' => 'credo-mutwa-zulus-e-repetilianos-parte-2.html',
		'309' => 'video-sobre-credo-mutwa.html',
		'310' => 'space-engine.html',
		'318' => 'gran-turismo-1.html',
		'319' => 'placa-de-video.html',
		'320' => 'hard-disk--hd-.html',
		'321' => 'ssd.html',
		'322' => 'm.2.html',
		'324' => 'software.html',
		'325' => 'water-cooler.html',
		'326' => 'placa-de-som.html',
		'327' => 'fonte-at-atx.html',
		'328' => 'playstation-1.html',
		'329' => 'playstation-2-1.html',
		'330' => 'playstation-3-1.html',
		'331' => 'emuladores-sony.html',
		'332' => 'goetia.html',
		'340' => 'veiculos.php',
		'343' => 'magia-goetica.html',
		'346' => 'aparelhos.html',
		'348' => '0-9.html',
		'350' => 'i.html',
		'351' => 'j.html',
		'352' => 'a.html',
		'353' => 'b.html',
		'354' => 'c.html',
		'355' => 'd.html',
		'356' => 'e.html',
		'357' => 'f.html',
		'358' => 'g.html',
		'359' => 'h.html',
		'360' => 'l.html',
		'361' => 'm.html',
		'362' => 'n.html',
		'363' => 'o.html',
		'364' => 'p.html',
		'365' => 'q.html',
		'366' => 'r.html',
		'367' => 's.html',
		'368' => 't.html',
		'369' => 'u.html',
		'370' => 'v.html',
		'371' => 'w.html',
		'372' => 'x.html',
		'373' => 'y.html',
		'374' => 'z.html',
		'375' => 'k.html',
		'376' => 'paises-livros-idiomas.html',
		'378' => '0-9-1.html',
		'379' => 'a-1.html',
		'380' => 'b-1.html',
		'381' => 'c-1.html',
		'382' => 'd-1.html',
		'383' => 'e-1.html',
		'384' => 'f-1.html',
		'385' => 'g-1.html',
		'386' => 'h-1.html',
		'387' => 'i-1.html',
		'388' => 'j-1.html',
		'389' => 'l-1.html',
		'390' => 'm-1.html',
		'391' => 'n-1.html',
		'392' => 'o-1.html',
		'393' => 'p-1.html',
		'394' => 'k-1.html',
		'395' => 'q-1.html',
		'396' => 'r-1.html',
		'397' => 's-1.html',
		'398' => 't-1.html',
		'399' => 'u-1.html',
		'400' => 'v-1.html',
		'401' => 'w-1.html',
		'402' => 'x-1.html',
		'403' => 'y-1.html',
		'404' => 'z-1.html',
		'406' => '0-9-2.html',
		'407' => 'a-2.html',
		'408' => 'b-2.html',
		'409' => 'c-2.html',
		'410' => 'd-2.html',
		'411' => 'e-2.html',
		'412' => 'f-2.html',
		'413' => 'g-2.html',
		'414' => 'h-2.html',
		'415' => 'i-2.html',
		'416' => 'j-2.html',
		'417' => 'l-2.html',
		'418' => 'm-2.html',
		'419' => 'n-2.html',
		'420' => 'o-2.html',
		'421' => 'p-2.html',
		'422' => 'q-2.html',
		'423' => 'r-2.html',
		'424' => 's-2.html',
		'425' => 't-2.html',
		'426' => 'u-2.html',
		'427' => 'v-2.html',
		'428' => 'w-2.html',
		'429' => 'x-2.html',
		'430' => 'y-2.html',
		'431' => 'z-2.html',
		'432' => 'k-2.html',
		'435' => 'xiaomi.html',
		'436' => 'marcas-smartphones.html',
		'438' => 'acessorios.html',
		'439' => 'smartwatch.html',
		'440' => 'tv-box.html',
		'447' => 'tv-8k.html',
		'449' => 'don-quijote-l.html',
		'450' => 'don-quijote-ll.html',
		'451' => 'do-mil-ao-milhao....html',
		'479' => 'o-milagre-da-manha.html',
		'480' => 'os-segredos-da-mente-milhonaria.html',
		'481' => 'a-sutil-arte-de-ligar-o-f--a-se....html',
		'482' => 'mais-esperto-que-o-diabo....html',
		'484' => 'xiaomi-redmi-note-7.html',
		'486' => 'xiaomi-mi8-lite.html',
		'487' => 'xiaomi-redmi-note-6-pro.html',
		'488' => 'xiaomi-mi-a2.html',
		'489' => 'xiaomi-redmi-6a.html',
		'490' => 'xiaomi-pocophone-f1.html',
		'491' => 'xiaomi-mi9.html',
		'493' => 'acessorios-smarthfone.html',
		'494' => 'smartphone-acessorios.html',
		'496' => 'baal.html',
		'497' => 'agares.html',
		'498' => 'vasago.html',
		'499' => 'baal---copiar-1.html',
		'500' => 'baal---copiar-2.html',
		'501' => 'baal---copiar-3.html',
		'502' => 'baal---copiar-4.html',
		'503' => 'baal---copiar-5.html',
		'504' => 'baal---copiar-6.html',
		'505' => 'baal---copiar-7.html',
		'506' => 'baal---copiar-8.html',
		'507' => 'baal---copiar-9.html',
		'508' => 'baal---copiar-10.html',
		'509' => 'baal---copiar-11.html',
		'510' => 'baal---copiar-12.html',
		'511' => 'baal---copiar-13.html',
		'512' => 'baal---copiar-14.html',
		'513' => 'baal---copiar-15.html',
		'514' => 'baal---copiar-16.html',
		'515' => 'baal---copiar-17.html',
		'516' => 'baal---copiar-18.html',
		'517' => 'baal---copiar-19.html',
		'518' => 'baal---copiar-20.html',
		'519' => 'baal---copiar-21.html',
		'520' => 'baal---copiar-22.html',
		'521' => 'baal---copiar-23.html',
		'522' => 'baal---copiar-24.html',
		'523' => 'baal---copiar-25.html',
		'524' => 'baal---copiar-26.html',
		'525' => 'baal---copiar-27.html',
		'526' => 'baal---copiar-28.html',
		'527' => 'baal---copiar-29.html',
		'528' => 'baal---copiar-30.html',
		'529' => 'baal---copiar-31.html',
		'530' => 'baal---copiar-32.html',
		'531' => 'baal---copiar-33.html',
		'532' => 'baal---copiar-34.html',
		'533' => 'baal---copiar-35.html',
		'534' => 'baal---copiar-36.html',
		'535' => 'baal---copiar-37.html',
		'536' => 'baal---copiar-38.html',
		'537' => 'baal---copiar-39.html',
		'538' => 'baal---copiar-40.html',
		'539' => 'baal---copiar-41.html',
		'540' => 'baal---copiar-42.html',
		'541' => 'baal---copiar-43.html',
		'542' => 'baal---copiar-44.html',
		'543' => 'baal---copiar-45.html',
		'544' => 'baal---copiar-46.html',
		'545' => 'baal---copiar-47.html',
		'546' => 'baal---copiar-48.html',
		'547' => 'neberius.html',
		'548' => 'aim.html',
		'549' => 'ipos.html',
		'550' => 'marax.html',
		'551' => 'purson.html',
		'552' => 'saleos.html',
		'553' => 'bathin.html',
		'554' => 'botis.html',
		'555' => 'zepar.html',
		'556' => 'eligos.html',
		'557' => 'leraje.html',
		'558' => 'beleth.html',
		'559' => 'sitri.html',
		'560' => 'gusion.html',
		'561' => 'buer.html',
		'562' => 'paimon.html',
		'563' => 'barbatos.html',
		'564' => 'amon.html',
		'565' => 'valefor.html',
		'566' => 'marbas.html',
		'567' => 'samigina.html',
		'568' => '72-demons.html',
		'569' => 'pagina-354.html',
		'573' => 'linus-torvalds.html',
		'574' => 'o-segrego.html',
		'575' => 'goetia---a-chave-menor-de-salomao.html',
		'576' => 'a-magia-da-serie-o-segredo.html',
		'577' => 'o-poder-da-serie-o-segredo.html',
		'578' => 'racas-alienigenas.html',
		'579' => 'playstation-4-1.html',
		'580' => 'smartphone.html',
		'581' => 'televisores.html',
		'583' => 'lg.html',
		'584' => 'motorola.html',
		'585' => 'sony.html',
		'586' => 'htc.html',
		'587' => 'alcatel.html',
		'588' => 'nokia.html',
		'589' => 'samsung.html',
		'590' => 'semp-toshiba.html',
		'591' => 'apple-1.html',
		'593' => 'asus.html',
		'594' => 'lenovo.html',
		'595' => 'multilaser.html',
		'596' => 'positivo.html',
		'597' => 'huawei.html',
		'613' => 'alcatel-1s.html',
		'614' => 'alcatel-1s-2020.html',
		'615' => 'android-2.x.x.html',
		'616' => 'android-3.x.x.html',
		'617' => 'android-4.x.x.html',
		'618' => 'android-5.x.x.html',
		'619' => 'android-6.x.x.html',
		'620' => 'android-7.x.x.html',
		'621' => 'android-8.x.x.html',
		'622' => 'android-9.x.x.html',
		'623' => 'android-10.x.x.html',
		'626' => 'alcatel-.......---copiar.html',
		'627' => 'alcatel-.......---copiar---copiar.html',
		'637' => 'i7-3770.html',
		'640' => 'doom--2016-.html',
		'641' => 'doom-classic.html',
		'642' => 'doom-ii.html',
		'644' => 'doom-versoes.html',
		'645' => 'doom-3.html',
		'646' => 'doom-64.html',
		'647' => 'ultimate-doom.html',
		'648' => 'doom-eternal.html',
		'649' => 'brutal-doom-64.html',
		'650' => 'brutal-doom.html',
		'651' => 'final-doom.html',
		'654' => 'pagina-inicial---mobile.php',
		'656' => 'apple-m.php',
		'657' => 'linux-m.php',
		'658' => 'microsoft-m.php',
		'323' => 'h-s-p-m.php',
		'659' => 'h-s-p.php',
		'660' => 'veiculos-m.php',
		'661' => 'ocultismo---espiritual-multidimensional-m.php',
		'662' => 'sobre-o-universo-m.php',
		'62' => 'lista-por-geracao.html',
		'663' => 'lista-por-geracao-m.php',
		'665' => 'televisores-m.html',
		'666' => 'smartphone-m.html'
	),
	'extendedScope' => array(
	)
);

/*****************
	PRODUCTS SEARCH
*****************/
$imSettings['search']['products'] = array(
);

/*****************
	IMAGES SEARCH
*****************/
$imSettings['search']['images'] = array(
	array(
		'title' => 'Apple',
		'description' => 'História, Produtos e Curiosidades.',
		'location' => '',
		'src' => 'images/Apple_Store_Carrousel_du_Louvre,_18_March_2011.png',
		'page' => 'index.php'
	),
	array(
		'title' => 'Microsoft',
		'description' => 'Sobre Microsoft',
		'location' => '',
		'src' => 'images/00.205.5.8pil_edit46.png',
		'page' => 'index.php'
	),
	array(
		'title' => 'Linux',
		'description' => 'Sobre Linux',
		'location' => '',
		'src' => 'images/qgis_linuxmint_instalacao-696x341.png',
		'page' => 'index.php'
	),
	array(
		'title' => 'H-P-S',
		'description' => '',
		'location' => '',
		'src' => 'images/Screenshot_2019-06-14-perifericos---Pesquisa-Google.png',
		'page' => 'index.php'
	),
	array(
		'title' => 'Universo',
		'description' => '',
		'location' => '',
		'src' => 'images/tecido-estampado-universo-galaxia-vestido-universo.png',
		'page' => 'index.php'
	),
	array(
		'title' => 'Ocultismo e Espiritual',
		'description' => '',
		'location' => '',
		'src' => 'images/passe.png',
		'page' => 'index.php'
	),
	array(
		'title' => 'Iphone',
		'description' => 'Aparelhos',
		'location' => '',
		'src' => 'images/iphone-8-iphone-8-plus-2017-9-1280x720.png',
		'page' => 'index.php'
	),
	array(
		'title' => 'Ipad',
		'description' => 'Aparelhos',
		'location' => '',
		'src' => 'images/tablet-apple-ipad-6-geracao-apple-a10-fusion-32gb-retina-9-7-ios-11-8-mp-photo511420959-12-37-32.png',
		'page' => 'index.php'
	),
	array(
		'title' => 'Macintosh',
		'description' => 'História Macintosh',
		'location' => '',
		'src' => 'images/Macintosh_128k_transparency.png',
		'page' => 'index.php'
	),
	array(
		'title' => 'Ubuntu',
		'description' => 'Sobre Ubuntu',
		'location' => '',
		'src' => 'images/ubuntu.png',
		'page' => 'index.php'
	),
	array(
		'title' => 'Linux Mint',
		'description' => 'Sobre Linux Mint',
		'location' => '',
		'src' => 'images/mint.png',
		'page' => 'index.php'
	),
	array(
		'title' => 'Deepin',
		'description' => 'Sobre Deepin',
		'location' => '',
		'src' => 'images/1200px-Deepin_logo.svg.png',
		'page' => 'index.php'
	),
	array(
		'title' => 'Bill Gates',
		'description' => 'Sobre Bill Gates',
		'location' => '',
		'src' => 'images/XpgonN0X_400x400.jpg',
		'page' => 'index.php'
	),
	array(
		'title' => 'Windows Phone',
		'description' => 'Sobre Windows Phone',
		'location' => '',
		'src' => 'images/windows-phone-.png',
		'page' => 'index.php'
	),
	array(
		'title' => 'Windows',
		'description' => 'Sobre Windows',
		'location' => '',
		'src' => 'images/novo_windows_microsoft_1.jpg',
		'page' => 'index.php'
	),
	array(
		'title' => 'SKY-MAP',
		'description' => 'Link SKY-MAPS',
		'location' => '',
		'src' => 'images/skymap.jpg',
		'page' => 'index.php'
	),
	array(
		'title' => 'História dos Mapas',
		'description' => '',
		'location' => '',
		'src' => 'images/Recurso170.jpg',
		'page' => 'index.php'
	),
	array(
		'title' => 'Sonda STEREO',
		'description' => '',
		'location' => '',
		'src' => 'images/Opera-Instantaneo_2020-04-28_163427_stereo-ssc.nascom.nasa.gov.png',
		'page' => 'index.php'
	),
	array(
		'title' => 'Computador',
		'description' => '',
		'location' => '',
		'src' => 'images/computador-gamer-knight-core-i7-9700k-rtx-2080-8gb-aeroluz-informatica-4-1-600x600.png',
		'page' => 'index.php'
	),
	array(
		'title' => 'Goétia',
		'description' => 'Sobre os Demons',
		'location' => '',
		'src' => 'images/Goetia_04.jpg',
		'page' => 'index.php'
	),
	array(
		'title' => 'Raças Alienigenas',
		'description' => '',
		'location' => '',
		'src' => 'images/cia-ataque-alienigena-27112018185100270.jpg',
		'page' => 'index.php'
	),
	array(
		'title' => 'Lista de Geração',
		'description' => 'Geração dos Consoles',
		'location' => '',
		'src' => 'images/consoles-varios.jpg',
		'page' => 'index.php'
	),
	array(
		'title' => 'Nintendo',
		'description' => 'Sobre a Nintendo',
		'location' => '',
		'src' => 'images/nintendo-logo.jpg',
		'page' => 'index.php'
	),
	array(
		'title' => 'Curso manutenção Smartphones',
		'description' => 'Melhor curso do mercado, aproveite!!!',
		'location' => '',
		'src' => 'images/Screenshot_2019-04-10-Conheca-a-Hotmart.jpg',
		'page' => 'historia-mac-os---mac-os-x.html'
	),
	array(
		'title' => 'Venda de Produtos Apple',
		'description' => 'Vendos dos produtos Apple até 2018 1° tri',
		'location' => 'Mundo',
		'src' => 'images/Apple-Products-Sales-Worldwide_e0zmcydv.png',
		'page' => 'iphone-e-versoes.html'
	),
	array(
		'title' => 'Xiaomi Redmi Note 7',
		'description' => '',
		'location' => '',
		'src' => 'images/Screenshot_2019-07-05-Celular,-Xiaomi,-Redmi-Note-7,-4GB-RAM,-64GB-Versao-Global,-Preto-Amazon-com-br-Celulares-e-Telefonia-1-.png',
		'page' => 'xiaomi-redmi-note-7.html'
	),
	array(
		'title' => 'Xiaomi Mi8 Lite',
		'description' => '',
		'location' => '',
		'src' => 'images/Screenshot_2019-07-05-Smartphone-Xiaomi-Mi8-Lite-64GB-4GB-RAM-Tela-6-26-,-4G,-Preto-Amazon-com-br-Celulares-e-Telefonia-1-.png',
		'page' => 'xiaomi-mi8-lite.html'
	),
	array(
		'title' => 'Xiaomi Redmi Note 6 Pro',
		'description' => '',
		'location' => '',
		'src' => 'images/Screenshot_2019-07-05-Smartphone-Xiaomi-Redmi-Note-6-Pro-4GB-64GB-4G---Preto-Amazon-com-br-Celulares-e-Telefonia-1-.png',
		'page' => 'xiaomi-redmi-note-6-pro.html'
	),
	array(
		'title' => 'Xiaomi Mi8 Lite',
		'description' => '',
		'location' => '',
		'src' => 'images/Screenshot_2019-07-06-Celular-Xiaomi-Mi-A2-MiA2-Snapdragon-660-Camera-Frontal-20MP,-64-GB,-4-RAM--Preto--Amazon-com-br-Celu-...-.png',
		'page' => 'xiaomi-mi-a2.html'
	),
	array(
		'title' => 'Xiaomi Redmi Note 6 Pro',
		'description' => '',
		'location' => '',
		'src' => 'images/Screenshot_2019-07-06-Smartphone-Xiaomi-Redmi-6A-Global-Tela-5-45-Camera-13MP-Face-Unlock--Preto-2-16GB--Amazon-com-br-Celu-...-.png',
		'page' => 'xiaomi-redmi-6a.html'
	),
	array(
		'title' => 'Xiaomi Redmi Note 7',
		'description' => '',
		'location' => '',
		'src' => 'images/Screenshot_2019-07-06-Xiaomi-Pocophone-F1-128-GB-Amazon-com-br-Celulares-e-Telefonia.png',
		'page' => 'xiaomi-pocophone-f1.html'
	),
	array(
		'title' => 'Xiaomi Redmi Note 7',
		'description' => '',
		'location' => '',
		'src' => 'images/Screenshot_2019-07-06-Celular-Xiaomi-Mi-9-128GB-6GB-48MP-12-0-Snapdragon-855-NFC-Wireless-Fast-Charge-Tela-6,39-Cor-Black-P-...--1-.png',
		'page' => 'xiaomi-mi9.html'
	),
	array(
		'title' => 'Apple',
		'description' => 'História, Produtos e Curiosidades.',
		'location' => '',
		'src' => 'images/Apple_Store_Carrousel_du_Louvre,_18_March_2011_nsofnpau.png',
		'page' => 'pagina-inicial---mobile.php'
	),
	array(
		'title' => 'Linux',
		'description' => '',
		'location' => '',
		'src' => 'images/qgis_linuxmint_instalacao-696x341_af32ofiu.png',
		'page' => 'pagina-inicial---mobile.php'
	)
);

/*****************
	VIDEOS SEARCH
*****************/
$imSettings['search']['videos'] = array(
);
$imSettings['search']['dynamicobjects'] = array(

);

// End of file search.inc.php